services:
  js-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: js-app
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000"  # Exposed by Dockerfile
    # env_file: ./.env  # Uncomment if .env file exists
    # Add depends_on here if you add external services
    # networks: [appnet]  # Uncomment if you add more services that need to communicate

# No external services (databases, caches, etc.) detected in the project files or documentation.
# No volumes section included, as there are no persistent data requirements.
# No custom networks defined, as there is only one service.
